"use client";

import { motion } from "framer-motion";
import {
    ShieldCheck, AlertTriangle, MapPin, Truck,
    Droplets, Activity, FileText, CheckCircle2,
    ChevronRight, BarChart3, Info, BadgeAlert
} from "lucide-react";
import { Van } from "@/lib/mock-data";

export interface ReportData {
    metadata: {
        reportType: string;
        engine: string;
        timestamp: string;
        authority: string;
        status: string;
    };
    classification: {
        primary: string;
        subCategory: string;
        confidence: number;
        explanation: string;
    };
    riskAssessment: {
        level: "Low" | "Medium" | "High";
        recurrenceProbability: number;
        urgency: string;
        explanation: string;
    };
    diagnostic: {
        cause: string;
        analysis: string;
    };
    location: {
        type: string;
        historicalInsight: string;
    };
    vanAssignment: {
        vanName: string;
        vanId: string;
        distance: string;
        status: string;
    };
    segregation: {
        wet: number;
        dry: number;
        hazardous: number;
        handlingNotes: string;
    };
    actionPlan: {
        immediate: string;
        preventive: string;
    };
    impact: {
        healthRisk: string;
        escalationPrevention: string;
    };
    complianceNote: string;
    feedback: {
        allowed: boolean;
        correctionStored: boolean;
    };
}

export default function ReportView({ data, onDownload }: { data: ReportData, onDownload?: () => void }) {
    const containerVariants = {
        hidden: { opacity: 0 },
        visible: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    };

    const itemVariants = {
        hidden: { y: 20, opacity: 0 },
        visible: { y: 0, opacity: 1 }
    };

    return (
        <motion.div
            className="w-full max-w-4xl mx-auto space-y-8 pb-20"
            variants={containerVariants}
            initial="hidden"
            animate="visible"
        >
            {/* 1. Report Metadata & Header */}
            <motion.div variants={itemVariants} className="glass-card p-6 border-l-4 border-primary-green">
                <div className="flex justify-between items-start mb-4">
                    <div>
                        <h1 className="text-2xl font-bold text-white mb-1">{data.metadata.reportType}</h1>
                        <p className="text-sm text-gray-400">Generated by: <span className="text-primary-green font-mono">{data.metadata.engine}</span></p>
                    </div>
                    <div className="text-right">
                        <div className="bg-primary-green/20 text-primary-green px-3 py-1 rounded-full text-xs font-bold border border-primary-green/30">
                            {data.metadata.status}
                        </div>
                        <p className="text-xs text-gray-500 mt-2">{new Date(data.metadata.timestamp).toLocaleString()}</p>
                    </div>
                </div>
                <div className="flex items-center gap-2 text-sm text-gray-300">
                    <ShieldCheck className="w-4 h-4 text-primary-green" />
                    <span>Authority: {data.metadata.authority}</span>
                </div>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* 2. Waste Categorization */}
                <motion.div variants={itemVariants} className="glass-card p-6">
                    <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                        <Activity className="w-5 h-5 text-primary-blue" />
                        Classification
                    </h3>
                    <div className="space-y-4">
                        <div>
                            <p className="text-xs text-gray-400 uppercase tracking-wider mb-1">Primary Category</p>
                            <p className="text-xl font-semibold text-white">{data.classification.primary}</p>
                            <p className="text-sm text-primary-blue/80">{data.classification.subCategory}</p>
                        </div>
                        <div>
                            <div className="flex justify-between items-center mb-1">
                                <p className="text-xs text-gray-400 uppercase tracking-wider">AI Confidence</p>
                                <span className="text-xs font-bold text-primary-green">{data.classification.confidence}%</span>
                            </div>
                            <div className="w-full bg-white/10 h-1.5 rounded-full overflow-hidden">
                                <motion.div
                                    initial={{ width: 0 }}
                                    animate={{ width: `${data.classification.confidence}%` }}
                                    className="h-full bg-primary-green shadow-[0_0_10px_#00f260]"
                                />
                            </div>
                        </div>
                        <p className="text-sm text-gray-400 leading-relaxed italic border-l-2 border-white/10 pl-3">
                            "{data.classification.explanation}"
                        </p>
                    </div>
                </motion.div>

                {/* 3. Risk Assessment */}
                <motion.div variants={itemVariants} className="glass-card p-6 overflow-hidden relative">
                    <div className={`absolute top-0 right-0 w-24 h-24 blur-3xl opacity-20 ${data.riskAssessment.level === "High" ? "bg-risk-red" :
                        data.riskAssessment.level === "Medium" ? "bg-warning-amber" : "bg-primary-green"
                        }`} />

                    <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                        <BadgeAlert className={`w-5 h-5 ${data.riskAssessment.level === "High" ? "text-risk-red" :
                            data.riskAssessment.level === "Medium" ? "text-warning-amber" : "text-primary-green"
                            }`} />
                        Risk Assessment
                    </h3>
                    <div className="space-y-4 relative z-10">
                        <div className="flex items-center gap-4">
                            <div className={`px-4 py-2 rounded-lg font-bold ${data.riskAssessment.level === "High" ? "bg-risk-red/20 text-risk-red border border-risk-red/30" :
                                data.riskAssessment.level === "Medium" ? "bg-warning-amber/20 text-warning-amber border border-warning-amber/30" :
                                    "bg-primary-green/20 text-primary-green border border-primary-green/30"
                                }`}>
                                {data.riskAssessment.level} Risk
                            </div>
                            <div>
                                <p className="text-xs text-gray-400 uppercase tracking-wider">Recurrence Prob.</p>
                                <p className="text-lg font-semibold">{data.riskAssessment.recurrenceProbability}%</p>
                            </div>
                        </div>
                        <div>
                            <p className="text-xs text-gray-400 uppercase tracking-wider mb-1">Urgency Status</p>
                            <p className="text-sm text-white font-medium">{data.riskAssessment.urgency}</p>
                        </div>
                        <p className="text-sm text-gray-400 leading-relaxed">
                            {data.riskAssessment.explanation}
                        </p>
                    </div>
                </motion.div>
            </div>

            {/* 4. AI Diagnostic & Cause Analysis */}
            <motion.div variants={itemVariants} className="glass-card p-6">
                <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                    <Info className="w-5 h-5 text-primary-green" />
                    AI Diagnostic & Cause Analysis
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="md:col-span-1">
                        <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Primary Cause</p>
                        <div className="inline-block bg-white/10 px-3 py-2 rounded-lg border border-white/10 text-primary-green font-medium">
                            {data.diagnostic.cause}
                        </div>
                    </div>
                    <div className="md:col-span-2">
                        <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Structural Analysis</p>
                        <div className="text-sm text-gray-300 leading-relaxed bg-black/30 p-4 rounded-xl border border-white/5 whitespace-pre-wrap">
                            {data.diagnostic.analysis}
                        </div>
                    </div>
                </div>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* 5. Location Intelligence */}
                <motion.div variants={itemVariants} className="glass-card p-6">
                    <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                        <MapPin className="w-5 h-5 text-primary-blue" />
                        Location Intelligence
                    </h3>
                    <div className="space-y-4">
                        <div>
                            <p className="text-xs text-gray-400 uppercase tracking-wider mb-1">Zone Type</p>
                            <p className="text-sm font-medium capitalize">{data.location.type}</p>
                        </div>
                        <div>
                            <p className="text-xs text-gray-400 uppercase tracking-wider mb-1">Historical Pattern</p>
                            <p className="text-sm text-gray-300 leading-relaxed">{data.location.historicalInsight}</p>
                        </div>
                    </div>
                </motion.div>

                {/* 6. Waste Collection Van Assignment */}
                <motion.div variants={itemVariants} className="glass-card p-6 border-t-4 border-primary-blue">
                    <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                        <Truck className="w-5 h-5 text-primary-blue" />
                        Van Assignment (Kuppai Vandi)
                    </h3>
                    <div className="flex items-center justify-between p-4 bg-primary-blue/10 rounded-xl border border-primary-blue/20">
                        <div>
                            <p className="text-sm font-bold text-white">{data.vanAssignment.vanName}</p>
                            <p className="text-xs text-gray-400">ID: {data.vanAssignment.vanId} • Proximity: {data.vanAssignment.distance}</p>
                        </div>
                        <div className="flex flex-col items-end">
                            <span className="text-xs font-bold text-primary-blue bg-primary-blue/20 px-2 py-1 rounded uppercase">
                                {data.vanAssignment.status}
                            </span>
                            <div className="flex items-center mt-2 text-[10px] text-gray-500">
                                <div className="w-1.5 h-1.5 rounded-full bg-primary-blue animate-pulse mr-1" />
                                Live Tracking Enabled
                            </div>
                        </div>
                    </div>
                </motion.div>
            </div>

            {/* 7. Waste Segregation Analysis */}
            <motion.div variants={itemVariants} className="glass-card p-6">
                <h3 className="text-lg font-bold mb-6 flex items-center gap-2">
                    <PieChartIcon className="w-5 h-5 text-warning-amber" />
                    Segregation Analysis
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                    <div className="grid grid-cols-3 gap-4">
                        {[
                            { label: "Wet", val: data.segregation.wet, color: "bg-primary-green", text: "text-primary-green" },
                            { label: "Dry", val: data.segregation.dry, color: "bg-primary-blue", text: "text-primary-blue" },
                            { label: "Hazard", val: data.segregation.hazardous, color: "bg-risk-red", text: "text-risk-red" }
                        ].map((s, i) => (
                            <div key={i} className="text-center">
                                <div className="relative w-16 h-16 mx-auto mb-2 flex items-center justify-center">
                                    <svg className="w-full h-full -rotate-90">
                                        <circle cx="32" cy="32" r="28" fill="none" stroke="currentColor" strokeWidth="4" className="text-white/5" />
                                        <motion.circle
                                            cx="32" cy="32" r="28" fill="none" stroke="currentColor" strokeWidth="4"
                                            strokeDasharray={175.9}
                                            initial={{ strokeDashoffset: 175.9 }}
                                            animate={{ strokeDashoffset: 175.9 - (175.9 * s.val) / 100 }}
                                            className={s.text}
                                        />
                                    </svg>
                                    <span className="absolute text-xs font-bold">{s.val}%</span>
                                </div>
                                <p className="text-[10px] uppercase tracking-widest text-gray-400">{s.label}</p>
                            </div>
                        ))}
                    </div>
                    <div className="bg-white/5 p-4 rounded-xl border border-white/10">
                        <p className="text-xs text-gray-400 uppercase tracking-wider mb-2 font-bold">Handling Considerations</p>
                        <p className="text-sm text-gray-300 leading-relaxed italic">
                            "{data.segregation.handlingNotes}"
                        </p>
                    </div>
                </div>
            </motion.div>

            {/* 8. Recommended Municipal Action Plan */}
            <motion.div variants={itemVariants} className="glass-card p-6 border-l-4 border-warning-amber">
                <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                    <CheckCircle2 className="w-5 h-5 text-warning-amber" />
                    Recommended Municipal Action Plan
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="bg-warning-amber/10 p-4 rounded-xl border border-warning-amber/20">
                        <div className="flex items-center gap-2 mb-2 text-warning-amber">
                            <Activity className="w-4 h-4" />
                            <h4 className="text-sm font-bold uppercase tracking-tight">Immediate Action</h4>
                        </div>
                        <p className="text-sm text-gray-300 leading-relaxed">{data.actionPlan.immediate}</p>
                    </div>
                    <div className="bg-primary-green/10 p-4 rounded-xl border border-primary-green/20">
                        <div className="flex items-center gap-2 mb-2 text-primary-green">
                            <ShieldCheck className="w-4 h-4" />
                            <h4 className="text-sm font-bold uppercase tracking-tight">Preventive Strategy</h4>
                        </div>
                        <p className="text-sm text-gray-300 leading-relaxed">{data.actionPlan.preventive}</p>
                    </div>
                </div>
            </motion.div>

            {/* 9 & 10. Health Impact & Compliance */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <motion.div variants={itemVariants} className="glass-card p-6 bg-risk-red/5">
                    <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                        <Droplets className="w-5 h-5 text-risk-red" />
                        Public Health & Environment
                    </h3>
                    <div className="space-y-4">
                        <div>
                            <p className="text-xs text-gray-400 uppercase tracking-wider mb-1">Health Risk Status</p>
                            <p className={`text-sm font-bold ${data.impact.healthRisk === "Low" ? "text-primary-green" : "text-risk-red"}`}>
                                {data.impact.healthRisk} Risk Level
                            </p>
                        </div>
                        <p className="text-sm text-gray-400 leading-relaxed">
                            {data.impact.escalationPrevention}
                        </p>
                    </div>
                </motion.div>

                <motion.div variants={itemVariants} className="glass-card p-6 flex flex-col justify-center items-center text-center">
                    <div className="w-12 h-12 bg-primary-green/20 rounded-full flex items-center justify-center mb-4">
                        <FileText className="w-6 h-6 text-primary-green" />
                    </div>
                    <h3 className="text-sm font-bold uppercase tracking-widest text-primary-green mb-2">Compliance & Audit Note</h3>
                    <p className="text-xs text-gray-500 leading-relaxed italic">
                        {data.complianceNote}
                    </p>
                    <div className="mt-4 pt-4 border-t border-white/10 w-full flex justify-center gap-4">
                        <button
                            onClick={onDownload}
                            className="text-[10px] text-primary-green hover:text-white transition-colors uppercase font-bold tracking-tighter"
                        >
                            Download Institutional Report
                        </button>
                        <button
                            onClick={() => alert("Audit Link Copied to Clipboard.")}
                            className="text-[10px] text-gray-400 hover:text-white transition-colors uppercase font-bold tracking-tighter"
                        >
                            Share Audit Link
                        </button>
                    </div>
                </motion.div>
            </div>

            {/* 11. AI Feedback & Correction */}
            {data.feedback.allowed && (
                <motion.div variants={itemVariants} className="glass-card p-4 border-dashed border-white/20 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <BadgeAlert className="w-5 h-5 text-primary-blue/60" />
                        <p className="text-xs text-gray-400 italic">Discovered an inaccuracy? Authorized officials can provide feedback to improve the engine.</p>
                    </div>
                    <button
                        onClick={() => alert("Feedback Interface: You are logged in as an Authorized Official. Please enter the corrections for the 'Waste Type' or 'Root Cause'.")}
                        className="glass-button px-4 py-2 text-xs font-bold text-primary-blue hover:text-white"
                    >
                        Correct Report
                    </button>
                </motion.div>
            )}
        </motion.div>
    );
}

function PieChartIcon({ className }: { className?: string }) {
    return (
        <svg
            className={className}
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M21.21 15.89A10 10 0 1 1 8 2.83" />
            <path d="M22 12A10 10 0 0 0 12 2v10z" />
        </svg>
    );
}
